paths:
  /api/products:
    get:
      summary: Devuelve todos los productos.
      tags:
        - Products
      responses:
        "200":
          description: Devuelve todos los productos.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/product'
              example:
                message: Productos encontrados.
                results:
                  - _id: 60b4b0a9e6c3c2b4c8a7b8b2
                    title: Producto 1
                    description: Descripción del producto 1
                    price: 100
                    thumbnail:
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                    code: 1
                    stock: 10
                    category: Categoria 1
                  - _id: 60b4b0a9e6c3c2b4c8a7b8b3
                    title: Producto 2
                    description: Descripción del producto 2
                    price: 200
                    thumbnail:
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                    code: 2
                    stock: 20
                    category: Categoria 2
        "400":
          description: Bad request.
          content:
            application/json:
              example:
                error: error al solicitar productos
        "502":
          description: true,hubo un error
          content:
            application/json:
              example:
                error: true,hubo un error

    post:
      summary: Crea un producto en la base de datos
      description: Add product.
      tags:
        - Products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
            example:
              title: Producto 1
              description: Descripción del producto 1
              price: 100
              thumbnail:
                https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
              code: prueba11
              stock: 10
              category: Categoria 1
      responses:
        "200":
          description: Devuelve el producto creado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              example:
                message: Producto agregado exitosamente.
                product:
                  _id: 60b4b0a9e6c3c2b4c8a7b8b2
                  title: Producto 1
                  description: Descripción del producto 1
                  price: 100
                  thumbnail:
                    https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                  code: codigoprueba
                  stock: 10
                  category: Categoria 1
        "400":
          description: Bad request.
          content:
            application/json:
              example:
                error: error al solicitar productos
        "502":
          description: error en el servidor
          content:
            application/json:
              example:
                error: error

  /api/products/{productId}:
    put:
      description: Actualiza product con ID
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          description: Product ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
            example:
              title: Producto editado 1
              description: Descripción del producto editado 1
              price: 1012
              thumbnail:
                https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
              code: 1
              stock: 19
              category: Categoria 1
      responses:
        "200":
          description: Devuelve producto actualizado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              example:
                message: Producto actualizado
                product:
                  _id: 60b4b0a9e6c3c2b4c8a7b8b2
                  title: Producto editado 1
                  description: Descripción del producto editado 1
                  price: 1012
                  thumbnail:
                    https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                  code: 1
                  stock: 19
                  category: Categoria 1
        "400":
          description: Mala solicitud.
          content:
            application/json:
              example:
                error: error
        "502":
          description: error.
          content:
            application/json:
              example:
                error: error

    delete:
      description: Borrar el product por ID.
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          description: Product ID
      responses:
        "200":
          description: Devuelve el producto borrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
              example:
                message: Se ha eliminado el producto exitosamente.
                product:
                  _id: 60b4b0a9e6c3c2b4c8a7b8b2
                  title: Producto 1
                  description: Descripción del producto 1
                  price: 1012
                  thumbnail:
                    https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                  code: 1
                  stock: 19
                  category: Categoria 1
        "400":
          description: Bad request.
          content:
            application/json:
              example:
                error: error
        "502":
          description: error de servidor.
          content:
            application/json:
              example:
                error: producto no existe
components:
  schemas:
    product:
      type: object
      properties:
        _id:
          type: string
          description: Id autogenerado de Mongo
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        code:
          type: string
          description: Código del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: number
          description: Cantidad en stock del producto
        category:
          type: string
          description: Categoria a la que pertenece el producto
        thumbnail:
          type: string
          description: Links a las rutas de las imágenes del producto
        owner:
          type: string
          description: Datos de quien creó el producto en la base de datos
      required:
        - title
        - description
        - code
        - price
        - stock
        - category